# Flume tmux color variables.

%hidden thm_bg="#f2eff7"
%hidden thm_fg="#554e5d"
%hidden thm_black="#413b49"
%hidden thm_gray="#413b49"
%hidden thm_lgray="#817987"
%hidden thm_accent="#006b85"
%hidden thm_red="#a43b62"
%hidden thm_green="#256f24"
%hidden thm_yellow="#895c00"
%hidden thm_blue="#006b9d"
%hidden thm_pink="#7540a3"
%hidden thm_cyan="#006b85"
%hidden thm_orange="#b5365b"
