# Flume tmux color variables.

%hidden thm_bg="#24212f"
%hidden thm_fg="#cbc5d2"
%hidden thm_black="#4b485a"
%hidden thm_gray="#4b485a"
%hidden thm_lgray="#746d7c"
%hidden thm_accent="#72b5bf"
%hidden thm_red="#dd789b"
%hidden thm_green="#84b39f"
%hidden thm_yellow="#d8a36b"
%hidden thm_blue="#72a8c7"
%hidden thm_pink="#b69bd2"
%hidden thm_cyan="#72b5bf"
%hidden thm_orange="#e88eaa"
