# Flume tmux color variables.

%hidden thm_bg="#f3ede8"
%hidden thm_fg="#58515d"
%hidden thm_black="#423d47"
%hidden thm_gray="#423d47"
%hidden thm_lgray="#817988"
%hidden thm_accent="#356f80"
%hidden thm_red="#974c68"
%hidden thm_green="#4b6d65"
%hidden thm_yellow="#80541f"
%hidden thm_blue="#356a83"
%hidden thm_pink="#6c538b"
%hidden thm_cyan="#356f80"
%hidden thm_orange="#a33d66"
