# Flume tmux color variables.

%hidden thm_bg="#232136"
%hidden thm_fg="#c9c5d9"
%hidden thm_black="#343949"
%hidden thm_gray="#343949"
%hidden thm_lgray="#67627d"
%hidden thm_accent="#73a6b6"
%hidden thm_red="#ee7583"
%hidden thm_green="#a4b78a"
%hidden thm_yellow="#dfb86b"
%hidden thm_blue="#6fa8dc"
%hidden thm_pink="#b99add"
%hidden thm_cyan="#8fc9d2"
%hidden thm_orange="#f48a94"
