# Flume Theme for Kitty
background            #f2eff7
foreground            #554e5d
selection_background  #413b49
selection_foreground  #fbf8fa
cursor                #006b85
cursor_text_color     #fbf8fa

# Black
color0  #413b49
color8  #706878

# Red
color1  #a43b62
color9  #b5365b

# Green
color2  #256f24
color10 #397515

# Yellow
color3  #895c00
color11 #965900

# Blue
color4  #006b9d
color12 #0071a3

# Magenta
color5  #7540a3
color13 #873a9d

# Cyan
color6  #006b85
color14 #00728c

# White
color7  #554e5d
color15 #413b49

# Tab bar
tab_bar_background        #ebe6f0
tab_bar_margin_color      #ebe6f0
active_tab_foreground     #554e5d
active_tab_background     #ddd6e3
active_tab_font_style     bold
inactive_tab_foreground   #706878
inactive_tab_background   #ebe6f0
inactive_tab_font_style   normal
