# Flume Theme for Kitty
background            #f3ede8
foreground            #58515d
selection_background  #423d47
selection_foreground  #fbf8fa
cursor                #356f80
cursor_text_color     #fbf8fa

# Black
color0  #423d47
color8  #58515d

# Red
color1  #974c68
color9  #a33d66

# Green
color2  #4b6d65
color10 #3f685f

# Yellow
color3  #80541f
color11 #8c4e19

# Blue
color4  #356a83
color12 #286782

# Magenta
color5  #6c538b
color13 #764b94

# Cyan
color6  #356f80
color14 #286c7e

# White
color7  #58515d
color15 #423d47

# Tab bar
tab_bar_background        #ebe3de
tab_bar_margin_color      #ebe3de
active_tab_foreground     #58515d
active_tab_background     #ded4d1
active_tab_font_style     bold
inactive_tab_foreground   #706976
inactive_tab_background   #ebe3de
inactive_tab_font_style   normal
